sudo: true

env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.6.22-f9533ba-linux-amd64.tar.xz

before_install:
  - openssl aes-256-cbc -K $encrypted_939c08394e3d_key -iv $encrypted_939c08394e3d_iv -in assets/server.key.enc -out assets/server.key -d
  - wget -qO- $URL | tar xJf -
  - ./heroku/install
  - export PATH=./heroku/$(pwd):$PATH

before_script:
  - export SFDX_DISABLE_ENCRYPTION=true
  - sfdx force --help
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername

script:
  - sfdx force:org:create -s -f config/workspace-scratch-def.json -a travisciorg
  - sfdx force:source:push -u travisciorg
  - sfdx force:apex:test:run -r tap
  - sleep 4m
  - sfdx force:org:delete -u travisciorg -p